BAH-4501 | test

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -40,16 +40,18 @@ jobs:
     runs-on: ubuntu-latest
     env:
       ORG_NAME: Bahmni
-      REPO_NAME: openmrs-distro-bahmni
+      REPOSITORY_NAME: openmrs-distro-bahmni
       EVENT_TYPE: fhir2_extension_updated
     steps:
-      - name: Dispatch OpenMRS Rebuild
+      - name: Create repository_dispatch
         run: |
+          echo ${{secrets.BAHMNI_USERNAME}}
+          echo ${{secrets.BAHMNI_PAT}}
           trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
-            if [ $trigger_result == 204 ];then
-              echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
-            else
-              echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
-              cat trigger_response.txt
-              exit 1
-            fi
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
